### ISSUE TITLE
Issue with Local attestation to Migration Enclave

### ISSUE THREAD

**Issue by sudharkrish** [SGX-Cloud/migration#1]
Firstly, thanks for your efforts related to migration.

I have one request, is it possible to provide a README file that has steps on how to setup and run the project sources.

**### Few changes, that I had to do:**

1. On my system, default port number 1300 was not available, so I had to change the code to use default value of 1302 for local port. Remote port 1301 works fine.
2. Enabled logs. 
3. Also added few extra debugs.
4. On my system PSE setup is NOT working currently, so calls to sgx_create_pse_session, was failing. I have temporarily commented that part of the code.
5. Also due to PSE setup issue, calls to sgx_*_monotonic_counters are currently failing.
6. But regardless of PSE issue, local attestation steps should still work, but they are failing with error, logs pasted below.

**### My Steps:**

1. Started Migration Enclave
skris14@skris14-Kabylake-Client-platform:~/mig_encl/migration$ ./migration_enclave/me_app &
token_path: /home/skris14/enclave.token
lport=1302, rport=1301

2. Checked if me_app came up fine.
skris14@skris14-Kabylake-Client-platform:~/mig_encl/migration$ ps aux | grep me_app
skris14    595  0.4  0.0 128208 10052 pts/34   S    16:47   0:00 ./migration_enclave me_app

3. Checked if the port numbers for local and remote port, for ME server are listening.
mig_encl/migration$ netstat -a | grep 1302
tcp        0      0 *:1302                  *:*                     LISTEN     
unix  3      [ ]         STREAM     CONNECTED     26281302 
mig_encl/migration$ netstat -a | grep 1301
tcp        0      0 *:1301                  *:*                     LISTEN     

4. Launched the sample app, and used the -t option, to do a self-test(but here the local attestation fails):

### **Log of Local attestation error message:**

[ENCLAVE] [MLib] [MIGRATE] Migrating to 127.0.0.1
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [MIGRATION] Sending Migration data to ME....
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 100, ip=127.0.0.1, port=1302
Error sending message! Bad file descriptor
Received data has not expected size: 21605520 != 576
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
[ENCLAVE] [MLib] closing connection with ME at 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATE] Sending migration with return code: 16391

**Since the ./app -t test, seems to start 4 enclave instances, using netstat, I can see that those 4 instances, have their socket connection to Migration Enclave server, in TIME_WAIT state, for some time.  After some time, those 4 socket connections get terminated.**

skris14@skris14-Kabylake-Client-platform:~/mig_encl/migration$ netstat -a | grep 1302
tcp        0      0 *:1302                  *:*                     LISTEN     
tcp        0      0 localhost:33090         localhost:1302          TIME_WAIT  
tcp        0      0 localhost:33092         localhost:1302          TIME_WAIT  
tcp        0      0 localhost:33096         localhost:1302          TIME_WAIT  
tcp        0      0 localhost:33094         localhost:1302          TIME_WAIT  

### **Full Detailed Log:**

skris14@skris14-Kabylake-Client-platform:~/mig_encl/migration$ ./sample_app/app -t
g_token_path: /home/skris14/enclave.token
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=2 
SK_Debug: establish_pse_session:172: 
migration_size = 5956
sealed blob length = 200560
Setting up environment done
Testing a full self-enclosed two hop migration:
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=3 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 0, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [INIT] Creating new instance...
[ENCLAVE] [MLib] [INIT] New sealing key generated
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [INIT] Creating new instance...DONE
Init returned: 0
[TEST CREATE COUNTER]
Counter created: Return code 4008, ID:0 with value 0
Increasing counter 0 to 2
[ENCLAVE] [MLib] [INCREMENT_COUNTER] Incremented counter with ID:0
Current value: 0. 2 to go.
[ENCLAVE] [MLib] [INCREMENT_COUNTER] Incremented counter with ID:0
Current value: 0. 2 to go.
done
[ENCLAVE] [MLib] [READ_COUNTER] Read counter with ID:0
Counter read: Return code 4008, ID:0 has value 0
[TEST CREATE COUNTER]
Counter created: Return code 4008, ID:0 with value 0
Increasing counter 0 to 0
done
[ENCLAVE] [MLib] [READ_COUNTER] Read counter with ID:0
Counter read: Return code 4008, ID:0 has value 0
[ENCLAVE] [MLib] [MIGRATE] Migrating to 127.0.0.1
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [MIGRATION] Sending Migration data to ME....
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 100, ip=127.0.0.1, port=1302
Error sending message! Bad file descriptor
Received data has not expected size: 21605520 != 576
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
[ENCLAVE] [MLib] closing connection with ME at 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATE] Sending migration with return code: 16391
Migrate returned: 4007
Rebuilding enclave to test migration functionality...
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=4 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 2, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATION] Receiving Migration...
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 100, ip=127.0.0.1, port=1302
Error sending message! Bad file descriptor
Received data has not expected size: 21605520 != 576
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
Init returned: 4007
Testing counters
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
Keep migrating to test two hop migration...
[ENCLAVE] [MLib] [MIGRATE] Migrating to 127.0.0.1
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [MIGRATION] Sending Migration data to ME....
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 100, ip=127.0.0.1, port=1302
Error sending message! Bad file descriptor
Received data has not expected size: 21621504 != 576
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
[ENCLAVE] [MLib] closing connection with ME at 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATE] Sending migration with return code: 16391
Migrate returned: 4007
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=5 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 2, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATION] Receiving Migration...
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 100, ip=127.0.0.1, port=1302
Error sending message! Bad file descriptor
Received data has not expected size: 21606112 != 576
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
Init returned: 4007
Testing and then deleting counters
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
Error deleting counter 0 with error code 11002
####### ERROR deleting counter 0
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
Error deleting counter 0 with error code 11002

**Comment by fritzalder** [comment]
Hi and thanks for your interest.
Yes, a Readme would be a nice addition. We did not have the time to set things up correctly but you are right, we should fix this soon.

Regarding your problem, I am confused that your -t flag creates 4 enclaves. Looking at sample -> main.cpp -> line 205, it should only create 3 enclaves but only have 1 running at any given time.

Secondly, you are basically getting a bad file descriptor error in your networking messages. You might want to log some more when the socket gets opened, maybe there is your problem. The error you get will happen in sgx_utils/libs/lib_la/untrusted/ula.cpp around line 97-109 (The error "Received data has not expected size: " is in line 125 so I guess something before goes wrong but is not thrown correctly). Can you maybe add some log messages around those lines and tell me if you find anything of interest?

As this is research code and we are now busy with other projects, we can not really give in-depth support for this library. But I will see that I write up a Readme soon and I am happy to help with troubleshooting.

Cheers,
Fritz

**Comment by sudharkrish** [comment]
Hi Fritz,

Thanks for your reply. 
I was doing some socket level debugging, so took some time to reply back.

**This may not make sense, but I noticed that when I used socket related code for asio::write in send_message and asio::read in read_message, within the same function->la_session_request_ocall(..),
, that is without passing soket pointer to send_message_read_response, 
then the asio::write and asio::read works fine.** 

**When passing socket object as an argument to send_message_read_response, which then internally calls->send_message and read_message, then the same code fails to do asio::write and asio::read. For asio::write, error is EBADF(Bad file descriptor).
For asio::read, error is EBADMSG**

**Here is a snippet of code changes, that I did to prove, what I am saying above:**
/*
 * contact remote enclave to get session id and dh message1
 */
```
ATTESTATION_STATUS la_session_request_ocall(
        remote_enclave_t *dest,
        sgx_dh_msg1_t *dh_msg1,
        uint32_t *session_id)
{
    uint32_t status = 0;
    sgx_status_t ret = SGX_SUCCESS;
    message_t msg, msg_resp;
    boost::system::error_code error;

    sgx_dh_msg1_t response_dh;

#ifdef SK_DEBUG
    printf("%s, %d, ip=%s, port=%s, port_int=%d\n",
                    __func__, __LINE__, dest->ip, dest->port, atoi(dest->port));
#endif    
    try 
    {   
    boost::system::error_code error;
        boost::asio::io_service io_service;
        tcp::resolver resolver(io_service);
        tcp::resolver::query query(dest->ip, dest->port);
        tcp::resolver::iterator endpoint_iterator = resolver.resolve(query);

        tcp::socket* socket(new tcp::socket(io_service));
        //socket->non_blocking(false);
        boost::asio::connect(*socket, endpoint_iterator);

    printf("%s, %d, ip=%s, port=%s, port_int=%d\n",
                    __func__, __LINE__, dest->ip, dest->port, atoi(dest->port));

#ifdef SK_DEBUG

    // Prepare a DH request message and send it
    msg.size_encrypted = 0;
    msg.size_plaintext = 0;
    msg.type = NETWORK_DH_REQUEST;
    msg.session_id = 0;
    msg.data_encrypted = NULL;

    boost::array<uint32_t, MESSAGE_HEADER_SIZE> out_buf = {msg.size_encrypted, msg.size_plaintext, msg.type, msg.session_id};

    socket->write_some(boost::asio::buffer(out_buf, sizeof(out_buf)), error);

    if(error.value() != boost::system::errc::success)
    {
        std::cout << __func__ << __LINE__ << "Error sending message! " << error.message() << std::endl;
    }
    else
    {
        std::cout << __func__ << __LINE__ << "sent message! " << "size of out_buf=" << sizeof(out_buf)  << std::endl;
    }

    /*: same code in read_message, works fine here, but does NOT work
      within read_message, when it is using socket pointer, inside read_message. */
  boost::array<uint32_t, MESSAGE_HEADER_SIZE> buf;
  size_t len = boost::asio::read(*socket, boost::asio::buffer(buf), error);
  if(error.value() != boost::system::errc::success){
    printf("%s, %d, read failed, read len=%d, error.value=%d\n",
                    __func__, __LINE__, len, error.value());
  }
  else
  {
        printf("%s, %d, read success, read len=%d, \n",
                    __func__, __LINE__, len);
  }

#endif

```
**here is the log on the server side(shows it receives the initial DH request message from client, and it replied back):**
./migration_enclave/me_app 
token_path: /home/skris14/enclave.token
lport=1302, rport=1301
[ME] [LA] handle_local_message, 212: 
[ME] [LA] Sent DH1 message to peer, size_enc=576, type=1, session_id=0

**Here is the read from the client:**
skris14@skris14-Kabylake-Client-platform:~/mig_encl/migration$ ./sample_app/app -t
g_token_path: /home/skris14/enclave.token
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=2 
SK_Debug: establish_pse_session:172: 
migration_size = 5956
sealed blob length = 200560
Setting up environment done
Testing a full self-enclosed two hop migration:
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=3 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 0, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [INIT] Creating new instance...
[ENCLAVE] [MLib] [INIT] New sealing key generated
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [INIT] Creating new instance...DONE
Init returned: 0

**(Removed some debug logs related to counters..)**
**(You can see sent_message, and read_success, for asio::write and asio::read
For write->sent message! size of out_buf=16
For read->read_message, 74, read success, read len=16, msg->type=16
).**
[LA] Requesting local attestation from target
la_session_request_ocall, 95, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall, 110, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall131
sent message! size of out_buf=16
la_session_request_ocall, 145, read success, read len=16, 
la_session_request_ocall, 161, ip=127.0.0.1, port_int=1302
send_message_read_response, 32, msg-type=0
send_message_read_response, 51, about to call read_message
read_message, 74, read success, read len=16, msg->type=16

**Now, for example, if I commented out the code snippet for asio::read in la_session_request_ocall, and just kept the asio::write. Then in that case, all the 4 instances of enclave...can send initial asio::write message, but ME server replies back to all 4 incoming requests, but all 4 of them, fail to read the reply, when the code is run from within read_message api.**

**So commented out the following in ->la_session_request_ocall**
   ```
 /*: same code in read_message, works fine here, but does NOT work
      within read_message, when it is using socket pointer, inside read_message. 
  boost::array<uint32_t, MESSAGE_HEADER_SIZE> buf;
  size_t len = boost::asio::read(*socket, boost::asio::buffer(buf), error);
  if(error.value() != boost::system::errc::success){
    printf("%s, %d, read failed, read len=%d, error.value=%d\n",
                    __func__, __LINE__, len, error.value());
  }
  else
  {
        printf("%s, %d, read success, read len=%d, \n",
                    __func__, __LINE__, len);
  }
  */
```

**And added debugs in read_message**

```
boost::system::error_code
read_message(tcp::socket* s, message_t *msg){
  boost::system::error_code error;
  boost::array<uint32_t, MESSAGE_HEADER_SIZE> buf;

  size_t len = boost::asio::read(*s, boost::asio::buffer(buf), error);
  if(error.value() != boost::system::errc::success){
    printf("%s, %d, read failed, read len=%d, msg->type=%d, error.value=%d\n",
                    __func__, __LINE__, len, msg->type, error.value());
    return error;
  }
#ifdef SK_DEBUG  
  else
  {
        printf("%s, %d, read success, read len=%d, msg->type=%d\n",
                    __func__, __LINE__, len, msg->type);
  }
#endif
```

**here are the logs below for the above changes:
On the server side(it receives message from all 4 instances, and replies to all 4):**
./migration_enclave/me_app 
token_path: /home/skris14/enclave.token
lport=1302, rport=1301
[ME] [LA] handle_local_message, 212: 
[ME] [LA] Sent DH1 message to peer, size_enc=576, type=1, session_id=0
[ME] [LA] handle_local_message, 212: 
Gracefully shut down the connection.
[ME] [LA] handle_local_message, 212: 
[ME] [LA] Sent DH1 message to peer, size_enc=576, type=1, session_id=1
[ME] [LA] handle_local_message, 212: 
Error closing connection
[ME] [LA] handle_local_message, 212: 
[ME] [LA] Sent DH1 message to peer, size_enc=576, type=1, session_id=2
[ME] [LA] handle_local_message, 212: 
[ME] [LA] Sent DH1 message to peer, size_enc=576, type=1, session_id=3
TcpConnection::receiveMsg error at receive header: system:104 (size: 0)
TcpConnection::receiveMsg error at receive header: system:104 (size: 0)

**Here are the logs on the client side(you can see asio::read code in read_message fails..):
you can look for this message->read_message, 67, read failed, read len=0, msg->type=16, error.value=9
Here error.value=9, is for EBADMSG.**

**Here below are FULL log on client side:**
skris14@skris14-Kabylake-Client-platform:~/mig_encl/migration$ ./sample_app/app -t
g_token_path: /home/skris14/enclave.token
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=2 
SK_Debug: initialize_enclave:154: 
SK_Debug: initialize_enclave:160: 
SK_Debug: establish_pse_session:172: 
migration_size = 5956
sealed blob length = 200560
Setting up environment done
Testing a full self-enclosed two hop migration:
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=3 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 0, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [INIT] Creating new instance...
[ENCLAVE] [MLib] [INIT] New sealing key generated
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [INIT] Creating new instance...DONE
Init returned: 0
[TEST CREATE COUNTER]
Counter created: Return code 4008, ID:0 with value 0
Increasing counter 0 to 2
[ENCLAVE] [MLib] [INCREMENT_COUNTER] Incremented counter with ID:0
Current value: 0. 2 to go.
[ENCLAVE] [MLib] [INCREMENT_COUNTER] Incremented counter with ID:0
Current value: 0. 2 to go.
done
[ENCLAVE] [MLib] [READ_COUNTER] Read counter with ID:0
Counter read: Return code 4008, ID:0 has value 0
[TEST CREATE COUNTER]
Counter created: Return code 4008, ID:0 with value 0
Increasing counter 0 to 0
done
[ENCLAVE] [MLib] [READ_COUNTER] Read counter with ID:0
Counter read: Return code 4008, ID:0 has value 0
[ENCLAVE] [MLib] [MIGRATE] Migrating to 127.0.0.1
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [MIGRATION] Sending Migration data to ME....
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 95, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall, 110, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall131sent message! size of out_buf=16
la_session_request_ocall, 162, ip=127.0.0.1, port_int=1302
send_message_read_response, 32, msg-type=0
send_message_read_response, 51, about to call read_message
read_message, 67, read failed, read len=0, msg->type=16, error.value=9
Received data has not expected size: 1556769344 != 576
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
[ENCLAVE] [MLib] closing connection with ME at 127.0.0.1:1302
send_message, 119, size of out_buf=16, out[0]=0, out[1]=0, out[2]=224, out[3]=0
Tried to Send 16 bytes:0 0 e0
Sent 16 bytes:0 0 e0
[ENCLAVE] [MLib] [MIGRATE] Sending migration with return code: 16391
Migrate returned: 4007
Rebuilding enclave to test migration functionality...
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=4 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 2, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATION] Receiving Migration...
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 95, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall, 110, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall83sent message! size of out_buf=10
la_session_request_ocall, 162, ip=127.0.0.1, port_int=1302
send_message_read_response, 32, msg-type=0
send_message_read_response, 51, about to call read_message
read_message, 67, read failed, read len=0, msg->type=16, error.value=9
Received data has not expected size: 5cca6a10 != 240
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
Init returned: 4007
Testing counters
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
Keep migrating to test two hop migration...
[ENCLAVE] [MLib] [MIGRATE] Migrating to 127.0.0.1
[ENCLAVE] [MLib] [SEAL] - Sealed the internal library data
[ENCLAVE] [MLib] [MIGRATION] Sending Migration data to ME....
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 95, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall, 110, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall83sent message! size of out_buf=10
la_session_request_ocall, 162, ip=127.0.0.1, port_int=1302
send_message_read_response, 32, msg-type=0
send_message_read_response, 51, about to call read_message
read_message, 67, read failed, read len=0, msg->type=16, error.value=9
Received data has not expected size: 5cca6a40 != 240
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
[ENCLAVE] [MLib] closing connection with ME at 127.0.0.1:1302
send_message, 119, size of out_buf=16, out[0]=0, out[1]=0, out[2]=224, out[3]=0
Tried to Send 16 bytes:0 0 e0
Sent 16 bytes:0 0 e0
[ENCLAVE] [MLib] [MIGRATE] Sending migration with return code: 16391
Migrate returned: 4007
SK_Debug: initialize_enclave:126: opened token. 
SK_Debug: initialize_enclave:140: created enclave, global_eid=5 
SK_Debug: initialize_enclave:146: updated=0
SK_Debug: establish_pse_session:172: 
[ENCLAVE] [MLib] [INIT] [ENCLAVE] [MLib] [INIT] called with state 2, buffer size 5956, and ip:port as 127.0.0.1:1302
[ENCLAVE] [MLib] [MIGRATION] Receiving Migration...
[ENCLAVE] [MLib] initiating connection with ME at 127.0.0.1:1302
[LA] Requesting local attestation from target
la_session_request_ocall, 95, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall, 110, ip=127.0.0.1, port=1302, port_int=1302
la_session_request_ocall83sent message! size of out_buf=10
la_session_request_ocall, 162, ip=127.0.0.1, port_int=1302
send_message_read_response, 32, msg-type=0
send_message_read_response, 51, about to call read_message
read_message, 67, read failed, read len=0, msg->type=16, error.value=9
Received data has not expected size: 5cca6a10 != 240
Unknown error
[ENCLAVE] [MLib] Error initializing ME: 4007
Init returned: 4007
Testing and then deleting counters
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
Error deleting counter 0 with error code 11002
####### ERROR deleting counter 0
[TEST COUNTER] Read counter failed with 11002
####### ERROR testing counter 0
Error deleting counter 0 with error code 11002
####### ERROR deleting counter 0

**Comment by akurniko** [comment]
Hi,

can you please specify the version of Boost on your system. Thanks.

-Arseny

**Comment by sudharkrish** [comment]
Hi, Sorry for delayed reply.

Here below is the boost version on my Ubuntu 16.04 system.

dpkg -s libboost-dev | grep 'Version'
Version: 1.58.0.1ubuntu1
