### ISSUE TITLE
Can you help update the code to get it works with intel sgx sdk version  2.9 and later?

### ISSUE THREAD

**Issue by junyuanw** [SGX-Cloud/migration#4]
It reports a error when I try it with sgx sdk 2.9

root@nuc_sgx_dcap1:/home/junyuanw/sgx-migration/sgx-utils/libs/lib_tke# make
/opt/intel/sgxsdk/bin/x64/sgx_edger8r --trusted nrt_tke.edl \
        --search-path /opt/intel/sgxsdk/include \
        --trusted-dir   . \
        --untrusted-dir .
error: File not found within search paths: sgx_tae_service.edl

Makefile:166: recipe for target 'nrt_tke_t.c' failed
make: *** [nrt_tke_t.c] Error 255

**Comment by idan2402** [comment]
Having an issue with that as well. The exact same error when trying to `make -B all` in order to install the gsx-utils. Maybe it's something with sgx-utils itself?

**Comment by fritzalder** [comment]
Yes I am afraid the sgx utils were a nice idea at the start but have quickly become obsolete with the other SDKs coming up and things like remote attestation becoming way easier than what we did. So there is no real future for the sgx_utils and I am afraid it does not really make sense to keep supporting them. The core code inside the enclave should be rather portable across enclaves, the only thing that gives all these issues is the networking outside of the enclave..

If you have specific uses for the migration code feel free to send me an email or reach out, I'd be happy to take a look. But with this being an obsolete research prototype I fear there will always be some issues with it.

**Comment by idan2402** [comment]
> 
> 
> Yes I am afraid the sgx utils were a nice idea at the start but have quickly become obsolete with the other SDKs coming up and things like remote attestation becoming way easier than what we did. So there is no real future for the sgx_utils and I am afraid it does not really make sense to keep supporting them. The core code inside the enclave should be rather portable across enclaves, the only thing that gives all these issues is the networking outside of the enclave..
> 
> If you have specific uses for the migration code feel free to send me an email or reach out, I'd be happy to take a look. But with this being an obsolete research prototype I fear there will always be some issues with it.

Thank you very much! I would love to send an email :)

**Comment by idan2402** [comment]
I've sent you an email on the subject. I used the email on your site, I hope it's the correct one :)
